openapi: 3.0.0
info:
    title: Stock-Tracker
    version: 1.0.0
servers:
    - url: http://{{app_url}}
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
paths:
    /login_check:
        post:
            tags:
                - default
            summary: Login Check
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - password
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
                            example:
                                username: test@test.test
                                password: password
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json: {}
                '401':
                    description: Unauthorized response
    /register:
        post:
            tags:
                - default
            summary: Register
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - email
                                - password
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                            example:
                                email: test@test.test
                                password: password
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json: {}
    /stock:
        get:
            tags:
                - default
            summary: Stock
            security:
                - bearerAuth: []
            parameters:
                - name: q
                  in: query
                  required: true
                  schema:
                      type: string
                  example: IBM
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json: {}
    /stock/history:
        get:
            tags:
                - default
            summary: History
            security:
                - bearerAuth: []
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json: {}
